# Travis Configuration for lecture-source-py

sudo: false
language: python
dist: xenial

language: python

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - ls $HOME/build/QuantEcon/lecture-source-py/_build/website/doctrees/
  - wget https://repo.anaconda.com/archive/Anaconda3-2019.03-Linux-x86_64.sh -O anaconda3.sh
  - chmod +x anaconda3.sh
  - ./anaconda3.sh -b
  - export PATH=/home/travis/anaconda3/bin:$PATH
  - pwd

install:
  - pip install quantecon
  - pip install joblib
  - git clone https://github.com/QuantEcon/sphinxcontrib-jupyter.git
  - cd sphinxcontrib-jupyter && python setup.py install && cd ../
  - rm -rf sphinxcontrib-jupyter
  - make setup

cache:
  directories:
    - $HOME/build/QuantEcon/lecture-source-py/_build

script:
  - make website
